### ISSUE TITLE
Building off the sample code?

### ISSUE THREAD

**Issue by rgregg** [jsinh/onedrive-dotnet#5]
The OneDrive API explorer has an SDK like project that's implemented as PCL. Did you take a look at starting this with that implementation and improving it?

**Comment by jsinh** [comment]
@rgregg Thanks for reaching out.

I was not aware of the OneDrive API explorer initially when I started fiddling with the API and kick started this repo. But yes since few days I am.

I have took `QueryStringBuilder` from it which I wanted at the moment and help me revisit few ways I wish to architect the SDK / library.

My first and foremost goal is to learn myself few stuffs during the process of implementing it:
* Gain case-study based experience for developing something that can target as many platform as feasible.
* Understand and learn by observation on how to design a good WebAPI, there are many aspects of API you understand when you put yourself in the boots of the users who consumes it.
* Pamper my love for C# and .NET.
* Provide a helpful library to peers and commit to maintaining and supporting it.
* Practically learn best practices of using feature and aspects of GitHub and GIT during the process of developing something.
* Eventually use the outcomes of this SDK in the day-to-day development work where needed and applicable.

The more I dig into the API explorer / SDK project I find more interesting stuffs to learn and adapt. But I will also be using it to come up with more queries to the team and cross check if I am missing something or left out.

It is definitely a good ref. point to reach goal of this repo. efforts. Thanks.
